# .github/workflows/publish.yml
name: Publish to PyPI (release)

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # <- OIDC for Trusted Publishing
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Build (PEP 517)
        run: |
          python -m pip install --upgrade pip build
          python -m build

      - name: Publish to PyPI (OIDC)
        uses: pypa/gh-action-pypi-publish@release/v1
        # No password/secret needed with Trusted Publishing